/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

/**
 *
 * @author ltmer
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    Deck d;
    Card c1;
    Card c2;
    int correct;
    int round;
    boolean next;
    boolean newGame;
    public Interface() {
        initComponents();
        jButton1.setVisible(false);
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CardsLeft = new javax.swing.JLabel();
        Correct = new javax.swing.JLabel();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 152, 70, 100));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 152, 70, 100));

        jButton3.setText("Start Game!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click Which Card You Think is Higher!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        CardsLeft.setText("Round: ");
        jPanel1.add(CardsLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        Correct.setText("Number Correct:");
        jPanel1.add(Correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gameLogic(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gameLogic(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (next == true){
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png")));
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png")));
            jButton3.setVisible(false);
            round++;
            next = false;
            return;
        }
        
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png")));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png")));
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        result.setText("");
        correct = 0;
        round = 1;
        d = new Deck();
        d.shuffle();
        next = false;
        newGame = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gameLogic(int n){
        if(next == true || newGame==true){
            return;
        }
        c1 = d.getTopCard();
        c2 = d.getTopCard();
        int val1 = c1.getValue();
        int val2 = c2.getValue();
        
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(c1.getImage())));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(c2.getImage())));
        
        if(val1>val2){
            if(n==1){
                jLabel1.setText("Correct!");
                correct++;
            }else{
                jLabel1.setText("Incorrect :(");
            }
        }else{
            if(n==2){
                jLabel1.setText("Correct!");
                correct++;
            }else{
                jLabel1.setText("Incorrect :(");
            }
        }
        
        next = true;
        jButton3.setVisible(true);
        jButton3.setText("Next Round!");
        Correct.setText("Number Correct: " + correct);
        CardsLeft.setText("Round: " + round);
        
        if(round==10){
            jButton3.setText("New Game");
            result.setText(correct*10 + "% Correct");
            newGame=true;
            next=false;
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardsLeft;
    private javax.swing.JLabel Correct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
